name: plenty
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.0
  page_transition: "^1.0.9"
  google_fonts: ^1.1.1
  flutter_staggered_animations: "^0.1.2"
  flutter_staggered_grid_view: ^0.3.3
  transparent_image: ^1.0.0
  flutter_custom_dialog: ^1.0.20
  dropdown_formfield: ^0.1.3
  quiver: ^2.1.5
  animations: ^1.1.2
  image_picker: ^0.6.7+22
  auto_animated: ^2.1.0
  expandable: ^4.1.4
  flutter_collapse: ^0.1.1
  flutter_expand_view: ^1.6.1
  animated_text_kit: ^3.1.0
  sign_button: ^1.0.2
  auth_buttons: ^0.0.5
  video_player: ^0.10.11+2
  scroll_snap_list: ^0.4.1
  rubber: ^0.4.0
  flutter_svg: 0.19.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
  - assets/images/
  - assets/image/
  - assets/videos/


